theme: "hugo-PaperMod"
baseURL: "https://garbage-collector-gnk.netlify.app/"
languageCode: en-us
title: garbage-collector-gnk

markup:
  goldmark:
    renderer:
      unsafe: true
params:
  math: true
  homeInfoParams:
  	Title: "Garbage Collector GNK"
		Content: >
			Welcome to my blog.
			
			- **GNK** is a "gonk" droid in Star Wars. The garbage can one. :)
			
			- Check out my GitHub!
			
			- I'm using the [PaperMod](https://adityatelange.github.io/hugo-PaperMod/) Hugo theme.
	
	socialIcons:
		- name: github
			url: "https://github.com/bryce-carson/"

ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
