theme: "hugo-PaperMod"
baseURL: "https://garbage-collector-gnk.netlify.app/"
languageCode: en-us
title: garbage-collector-gnk

markup:
  goldmark:
    renderer:
      unsafe: true
params:
  math: true

ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
